# Generated by Django 3.2.5 on 2021-07-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_rename_image_name_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='image_name',
        ),
    ]
